{
  "services": {
    "devcontainer": {
      "build": "docker/devcontainer",
      "command": "sh -c 'while sleep 1; do :; done'",
      "init": true,
      "volumes": [
        ".:/workspaces/lazuli",
        "cabal:/home/haskell/.cabal",
        "cabal-store:/cabal-store"
      ],
      "working_dir": "/workspaces/lazuli"
    }
  },
  "volumes": {
    "cabal": null,
    "cabal-store": {
      "external": true
    }
  }
}
