[env]
  LAZULI_ENVIRONMENT = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.http_checks]]
    path = "/api/health-check"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
