{
  "jobs": {
    "build": {
      "name": "Build on ${{ matrix.platform }}",
      "runs-on": "${{ matrix.platform }}-${{ matrix.version }}",
      "steps": [
        {
          "uses": "actions/checkout@v3"
        }
      ],
      "strategy": {
        "matrix": {
          "include": [
            {
              "platform": "macos",
              "version": "12"
            },
            {
              "platform": "ubuntu",
              "version": "22.04"
            },
            {
              "platform": "windows",
              "version": "2022"
            }
          ]
        }
      }
    }
  },
  "name": "Workflow",
  "on": {
    "push": null,
    "schedule": [
      {
        "cron": "0 0 * * *"
      }
    ]
  }
}
